### ISSUE TITLE
AE2 Additions Fails to load correctly on server

### ISSUE THREAD

**Issue by Ghostipedia** [ADT-Team-com/AE2-Addition#4]
Forge Version : 1.18.2-40.1.51
AE2 Additions Version : AE2-Additions-1.18.2-0.1.1.jar
AE2 Version : appliedenergistics2-11.1.1.jar ( Also Attempted to try on appliedenergistics2-11.1.2.jar, issue persisted)
The Client, and Loading Singleplayer worlds works fine, the issue arises when attempting to launch a server, in this case my locally hosted server kneels over upon loading.

Crash logs have been provided

https://pastebin.com/xyfAyU7p

**Comment by SerStarStory** [comment]
Fixed
