### ISSUE TITLE
Crafting storage

### ISSUE THREAD

**Issue by castilio20** [ADT-Team-com/AE2-Addition#5]
![2022-06-14_14 20 21](https://user-images.githubusercontent.com/76228548/173570818-236d68f2-5463-402b-b8e8-3ec306fa61c1.png)
![2022-06-14_14 49 04](https://user-images.githubusercontent.com/76228548/173570834-1a54f19f-afb3-43cc-b164-5c233745f72a.png)
with your mod instaled the ae2 storage doesnt work only works yours

**Comment by SerStarStory** [comment]
Try the latest version.

**Comment by castilio20** [comment]
now it wroks thx
