### ISSUE TITLE
[1.18.2] Crash on start

### ISSUE THREAD

**Issue by Konstantinell** [ADT-Team-com/AE2-Addition#6]
I have a client  crash when this mod and mod [AE Additions - ExtraCells2 Fork](https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork) are install together. Separate both mods work good.
Applied Energistics 2 version 11.1.4
AE Additions - ExtraCells2 Fork version 3.1.1
AE2Additions version 0.1.2
Forge version 40.1.54

[crash-2022-07-16_22.05.37-client.txt](https://github.com/ADT-Team-com/AE2-Addition/files/9126454/crash-2022-07-16_22.05.37-client.txt)

[latest.log](https://github.com/ADT-Team-com/AE2-Addition/files/9126456/latest.log)

**Comment by SerStarStory** [comment]
HI. I read about your problem and i have to say that [AE Additions] use the same modid "ae2additions". Unfortunately, I can't help you...
