### ISSUE TITLE
AE2 Pattern Access Terminal does not recoginize Pattern Providers

### ISSUE THREAD

**Issue by Glitched-Fox-Studios** [ADT-Team-com/AE2-Addition#7]
Using ATM7 - To The Sky pack 1.0.8. The Pattern Terminal from AE2 only shows 1 single line of slots when it comes to your Pattern Providers. This means I must go directly to the Pattern Providers in order to modify the patterns.

![image](https://user-images.githubusercontent.com/75238752/196003497-895fad3e-385e-40cb-acb2-4b4f7c888aac.png)

As you can see from the above image, the Ultimate Smelting Factory has a Generation 5 Pattern Provider on it, but only the first 9 show in the Access Terminal. This issue also means it is impossible to use your providers in a Crafting Lotus as I would never be able to access the providers.

The version of AE2 with the above mod pack is 11.5.0.

**Comment by SerStarStory** [comment]
Thank you for an issue. I think i'll create new terminal especially for my providers

**Comment by SerStarStory** [comment]
Fixed in version 1.18.2-0.2
