### ISSUE TITLE
Possibly Incorrect Pattern Provider Gen 5 Recipe

### ISSUE THREAD

**Issue by shanoaice** [ADT-Team-com/AE2-Addition#8]
It seems like the ME Pattern Provider Generation 5 required a Gen 3 provider instead a Gen 4 provider. Is this intended or is this a bug?

**Comment by SerStarStory** [comment]
Thank you for an issue. I'll fix it.

**Comment by SerStarStory** [comment]
Fixed in version 1.18.2-0.2
