### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bypgomes** [ADT-Team-com/AE2-Addition#9]
When I have a ME Security Terminal in the system, I cannot put the ME Pattern Provider, they are broken as if the network were not mine, so I have to remove Security or break part of the system to be able to put it on the system.
![image](https://user-images.githubusercontent.com/29603439/199129643-01520ca2-fa48-40c4-b5e1-095984979c9a.png)

**Comment by SerStarStory** [comment]
Thank you for an issue. I'll fix it.

**Comment by SerStarStory** [comment]
Fixed in version 1.18.2-0.2
